from groq import Groq
from dotenv import load_dotenv
import os

load_dotenv()

api_key = os.getenv("GROQ_API_KEY")

if not api_key:
    raise ValueError(
        "GROQ_API_KEY is not set. Please add it to your .env file."
    )

client = Groq(api_key=api_key)

REQUIRED_SECTIONS = [
    "## Open Issues",
    "## Watch Items",
    "## Recent Fixes",
    "## Pending Actions"
]


def validate_output(text):
    """
    Ensure all required sections are present.
    """

    missing = []

    for section in REQUIRED_SECTIONS:

        if section not in text:
            missing.append(section)

    if missing:

        raise ValueError(
            f"LLM output missing sections: {', '.join(missing)}"
        )

    return True


def generate_handover_note(combined_text):
    """
    Generate a structured shift handover report
    from Discord and Ticket data.
    """

    prompt = f"""
You are a senior support engineer creating a shift handover report.

You will receive:
1. Discord chat messages
2. Ticket system data

Instructions:

- Analyze ONLY the provided data.
- Merge duplicate incidents appearing in both Discord and tickets.
- Do NOT repeat the same issue twice.
- Each bullet should describe ONE issue only.
- Keep bullets concise.
- Include ticket IDs or Discord timestamps when available.
- Use professional support-engineering language.

Generate EXACTLY the following markdown structure:

## Open Issues
- list unresolved issues

## Watch Items
- Include systems that may need continued monitoring.
- Explain WHY they should be monitored.

## Recent Fixes
- issues resolved during the shift

## Pending Actions
- actions the next shift must continue

DATA:
{combined_text}
"""

    last_error = None

    for attempt in range(3):

        try:

            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0.2,
                max_tokens=2000
            )

            result = response.choices[0].message.content

            validate_output(result)

            # Add professional ending
            result += """

---

📋 End of Handover Report

Generated by Shift Handover Note Generator.

✨ From incidents to insights.
Thank You. Have a Nice Day! 😊
"""

            return result

        except Exception as e:

            last_error = e

    raise RuntimeError(
        f"Failed to generate valid handover note after 3 attempts. Error: {last_error}"
    )